### PR TITLE
HerdDB Collections - do not perform Files#createDirectories at every page write

### LINKED ISSUE #418: HerdDB Collections  - do not perform Files#createDirectories at every page write
Under heavy load (frequent index page writes) Files#createDirectories adds too much overhead on the FS.

We can simply ensure that the directory for an index or for a page exists at boot and fail in case is is removed during server execution.

### PR DESCRIPTION
**Pull request by eolivelli**
closes #418

### CODE REVIEW

File: herddb-core/src/main/java/herddb/storage/DataStorageManager.java [hunk 1]
```diff
@@ -64,6 +64,10 @@
     public abstract List<Record> readPage(String tableSpace, String uuid, Long pageId)
         throws DataStorageManagerException, DataPageDoesNotExistException;
 
+    public abstract void ensureIndexDirectory(String tableSpace, String indexName) throws DataStorageManagerException;
```
Comment (diegosalvi) [inline herddb-core/src/main/java/herddb/storage/DataStorageManager.java]: DataStorageManager is some more "generic"... shouldn't be better a initIndex, bootIndex or prepareIndex?

indexName is unfortunately not really... true.. some index use uuid other a composite name. We can name it as uuid the is just little less misleading (because who use the uuid... has a name too... BRIN indexes for example)

File: herddb-core/src/main/java/herddb/storage/DataStorageManager.java [hunk 2]
```diff
@@ -64,6 +64,10 @@
...
+    
+    public abstract void ensureTableDirectory(String tableSpace, String uuid) throws DataStorageManagerException;
```
Comment (diegosalvi) [inline herddb-core/src/main/java/herddb/storage/DataStorageManager.java]: DataStorageManager is some more "generic"... shouldn't be better a initTable, bootTable or prepareTable?

File: herddb-core/src/main/java/herddb/storage/DataStorageManager.java [hunk 3]
```diff
@@ -64,6 +64,10 @@
     public abstract List<Record> readPage(String tableSpace, String uuid, Long pageId)
         throws DataStorageManagerException, DataPageDoesNotExistException;
 
+    public abstract void ensureIndexDirectory(String tableSpace, String indexName) throws DataStorageManagerException;
+
```
Comment (diegosalvi) [inline herddb-core/src/main/java/herddb/storage/DataStorageManager.java]: I cannot find invocation for BRIN indexes (they too use writeIndexPage if I remember well)

File: herddb-core/src/main/java/herddb/storage/DataStorageManager.java (hunk 1 above)
Comment (eolivelli) [reply herddb-core/src/main/java/herddb/storage/DataStorageManager.java]: renamed to "bootIndex"

File: herddb-core/src/main/java/herddb/storage/DataStorageManager.java (hunk 2 above)
Comment (eolivelli) [reply herddb-core/src/main/java/herddb/storage/DataStorageManager.java]: renamed to "bootTable"

File: herddb-core/src/main/java/herddb/storage/DataStorageManager.java (hunk 3 above)
Comment (eolivelli) [reply herddb-core/src/main/java/herddb/storage/DataStorageManager.java]: good catch ! added

**Comment by eolivelli** [comment]
@diegosalvi Travis is failing with this error, that I can reproduce on my laptop
```

lug 26, 2019 11:58:57 PM herddb.core.DBManager manageTableSpaces
GRAVE: cannot handle tablespace herd
java.lang.IllegalStateException: 
	at herddb.core.TableManager.cleanAndCompactPages(TableManager.java:2353)
	at herddb.core.TableManager.checkpoint(TableManager.java:2558)
	at herddb.core.TableManager.checkpoint(TableManager.java:2101)
	at herddb.core.TableSpaceManager.checkpoint(TableSpaceManager.java:1575)
	at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:299)
	at herddb.core.TableSpaceManager.start(TableSpaceManager.java:230)
	at herddb.core.DBManager.handleTableSpace(DBManager.java:534)
	at herddb.core.DBManager.manageTableSpaces(DBManager.java:1136)
	at herddb.core.DBManager.executeActivator(DBManager.java:1091)
	at herddb.core.DBManager.access$500(DBManager.java:115)
	at herddb.core.DBManager$Activator.run(DBManager.java:1039)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by eolivelli** [comment]
this is the error after rebasing to current master

```
GRAVE: cannot handle tablespace herd
java.lang.IllegalStateException: Data inconsistency! Found a clean page with dirty records based on PK data. It could be a key to page inconsistency (broken PK) or a page metadata inconsistency (failed to track dirty record on page metadata). Page: 1:140, Record Record{key=00000001, value=}
	at herddb.core.TableManager.cleanAndCompactPages(TableManager.java:2355)
	at herddb.core.TableManager.checkpoint(TableManager.java:2592)
	at herddb.core.TableManager.checkpoint(TableManager.java:2109)
	at herddb.core.TableSpaceManager.checkpoint(TableSpaceManager.java:1575)
	at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:299)
	at herddb.core.TableSpaceManager.start(TableSpaceManager.java:230)
	at herddb.core.DBManager.handleTableSpace(DBManager.java:534)
	at herddb.core.DBManager.manageTableSpaces(DBManager.java:1136)
	at herddb.core.DBManager.executeActivator(DBManager.java:1091)
	at herddb.core.DBManager.access$500(DBManager.java:115)
	at herddb.core.DBManager$Activator.run(DBManager.java:1039)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by eolivelli** [comment]
I can't reproduce the error on current master.
This is weird, investingating...

**Comment by eolivelli** [comment]
@diegosalvi  I found the problem, I had anticipated the boot of the PK and at every boot the PK started with 0 records !

**Comment by eolivelli** [comment]
@diegosalvi this patch should be good to go now,
backward compatibility tests found one last bug
