### PR TITLE
Correct empty pages flush, closes #423

### LINKED ISSUE #423: Divide by zero on new page flush
Bug report.

I got a divide by zero during a new page flush.

```
java.sql.SQLException: java.util.concurrent.CompletionException: java.lang.ArithmeticException: / by zero
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ArithmeticException: / by zero
        at herddb.core.PageSet$DataPageMetaData.<init>(PageSet.java:58)
        at herddb.core.PageSet.pageCreated(PageSet.java:139)
        at herddb.core.TableManager.flushNewPage(TableManager.java:815)
        at herddb.core.TableManager.flushNewPageForUnload(TableManager.java:763)
        at herddb.core.TableManager.lambda$unload$2(TableManager.java:711)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfPresent(ConcurrentHashMap.java:1822)
        at herddb.core.TableManager.unload(TableManager.java:704)
        at herddb.core.TableManager.allocateLivePage(TableManager.java:630)
        at herddb.core.TableManager.applyUpdate(TableManager.java:1728)
        at herddb.core.TableManager.onTransactionCommit(TableManager.java:1413)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:361)
        at herddb.core.TableSpaceManager.lambda$commitTransaction$16(TableSpaceManager.java:1692)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
        ... 5 more
```

It occurred on a fresh standalone installation of HerdDB.

### PR DESCRIPTION
**Pull request by diegosalvi**
Fix arithmetic divide by 0 found in #423 

Empty new pages flushed:
* will simply be discarded during page unload
* will be discarded during checkpoint ONLY if aren't the current active one

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

File: herddb-core/src/main/java/herddb/core/TableManager.java [hunk 1]
```diff
@@ -2607,6 +2642,13 @@ private TableCheckpoint checkpoint(double dirtyThreshold, double fillThreshold,
             /* *** New pages handling *** */
             /* ************************** */
 
+            /*
+             * Preleva la pagina dirty "corrente", può essere tenuta in memoria perché durante un checkpoint
```
Comment (eolivelli) [inline herddb-core/src/main/java/herddb/core/TableManager.java]: please write in English language

Comment (diegosalvi) [reply herddb-core/src/main/java/herddb/core/TableManager.java]: Oh! sorry, got carried away by documentation focus :D

Comment (diegosalvi) [reply herddb-core/src/main/java/herddb/core/TableManager.java]: Done
