### PR TITLE
JDBC Implement getBoolean/setBoolean for integer columns

### LINKED ISSUE #672: JDBC: Handle ResultSet#getBoolean with integer values (1=true,0=false)
**BUG REPORT**

1. Please describe the issue you observed:
getBoolean() on a integer column returns always "false" because we are using Boolean.parseBoolean.

These are the official JDBC specs:

```


 /**
     * Retrieves the value of the designated column in the current row
     * of this <code>ResultSet</code> object as
     * a <code>boolean</code> in the Java programming language.
     *
     * <P>If the designated column has a datatype of CHAR or VARCHAR
     * and contains a "0" or has a datatype of BIT, TINYINT, SMALLINT, INTEGER or BIGINT
     * and contains  a 0, a value of <code>false</code> is returned.  If the designated column has a datatype
     * of CHAR or VARCHAR
     * and contains a "1" or has a datatype of BIT, TINYINT, SMALLINT, INTEGER or BIGINT
     * and contains  a 1, a value of <code>true</code> is returned.
     *
     * @param columnIndex the first column is 1, the second is 2, ...
     * @return the column value; if the value is SQL <code>NULL</code>, the
     * value returned is <code>false</code>
     * @exception SQLException if the columnIndex is not valid;
     * if a database access error occurs or this method is
     *            called on a closed result set
     */
```

### PR DESCRIPTION
**Pull request by eolivelli**
Fixes #672

### CODE REVIEW

File: herddb-jdbc/src/main/java/herddb/jdbc/HerdDBResultSet.java [hunk 1]
```diff
@@ -235,7 +235,11 @@ public boolean getBoolean(int columnLabel) throws SQLException {
         fillLastValue(columnLabel);
         if (lastValue != null) {
             wasNull = false;
-            return Boolean.parseBoolean(lastValue.toString());
+            if (lastValue instanceof Number) {
```
Comment (eolivelli) [inline herddb-jdbc/src/main/java/herddb/jdbc/HerdDBResultSet.java:238]: this is actually the fix of getBoolean

File: herddb-core/src/main/java/herddb/sql/SQLRecordPredicate.java [hunk 2]
```diff
@@ -137,11 +137,20 @@ public static Object cast(Object value, int type) {
             switch (type) {
                 case ColumnTypes.INTEGER:
                 case ColumnTypes.NOTNULL_INTEGER:
+                    if (value instanceof Boolean) {
```
Comment (eolivelli) [inline herddb-core/src/main/java/herddb/sql/SQLRecordPredicate.java:140]: this is the fix for setBoolean
